config/routes.rb
WowWishlist::Application.routes.draw do

  resources :characters do
    collection do
      get 'search'
    end
  end
  
  resources :items do
    collection do
      get 'search'
    end
  end
  
  resources :users
  resources :realms,        :only => [:index]
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :bounds,        :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/admin',   :to => 'pages#admin'
  
  root :to => "pages#home"

  get "pages/contact"
  get "pages/search"

end

app/views/pages/admin.html.erb
<h1>Admin Panel</h1>
<div class="span-24">
	<h2 class="alt">Users</h2>
	<div>
	<%= will_paginate @users, :param_name => :page_user %>
	<table>
	  <% @users.each do |user|  %>
		<tr>
			<td><%= link_to user.name, user_path(user) %></td><td>Relationships: <%= user.relationships.count %></td><td>Items: <%= user.items.count %></td>
			<td><%= link_to "delete", user, :method => :delete, :confirm => "You sure?", :title => "Delete #{user.name}"%></td>
		</tr>
 	  <% end %>
	<table>
	<%= will_paginate @users, :param_name => :page_user %>
	</div>
</div>	

<div class"span-24">
	<h2 class="alt">Characters</h2>
	<%= will_paginate @characters, :param_name => :page_character %>
	<table>
	  <% @characters.each do |char|  %>
		<tr>
			<td><%= link_to char.name, character_path(char) %></td><td><%= char.realm.name %></td><td>Relationships: <%= char.owners.count %></td><td><%= char.realm.region %></td>
			<td><%= link_to "update", char, :method => :put, :confirm => "You sure?", :title => "Update #{char.name}"%></td>
			<td><%= link_to "delete", char, :method => :delete, :confirm => "You sure you want to DELETE #{char.name}?", :title => "Delete #{char.name}"%></td>
		</tr>
 	  <% end %>
	<table>
	<%= will_paginate @characters, :param_name => :page_character %>
</div>

<div class"span-24">
	<h2 class="alt">Items</h2>
	<%= will_paginate @items, :param_name => :page_item  %>
	<table>
	  <% @items.each do |item|  %>
		<tr>
			<td><%= item.id %></td><td><%= link_to item.name, item_path(item), :rel => "item=#{item.id}" %></td><td><%= item.itemLevel %></td><td>Bounds: <%= item.bounds.count %></td>
			<td><%= link_to "delete", item, :method => :delete, :confirm => "You sure you want to DELETE #{item.name}?", :title => "Delete #{item.name}"%></td>
		</tr>
 	  <% end %>
	<table>
	<%= will_paginate @items, :param_name => :page_item %>
</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h2>Welcome!</h2>
<p>The Woshlist is a place to keep track of your characters, and the items that 
that you want. I created based on my needs, to not want to keep spreadsheets, 
and bookmarks spread through different computers. With the Woshlist, you can 
claim your own toon, keep an eye on your guildmates or stalk your favorite 
Elitist Jerk raider...
<br /><br />
Get started in three easy steps:</p>

<ul>
	<li>create an <%= link_to 'new account', signup_path %></li>
	<li>Search for your <%= link_to 'character', characters_path %></li>
	<li>Search for the <%= link_to 'items', items_path %> you want!</li>
</ul>

<p>This is a on-going project, so suggestions and comments are always welcome!</p>

app/views/pages/search.html.erb
<h1>Search</h1>

<hr />

<div class="round box">
  <h3 class="caps">CHARACTERS</h3>
  <%= render 'characters/search_form' %>
</div>