config/routes.rb
WowWishlist::Application.routes.draw do

  resources :characters do
    collection do
      get 'search'
    end
  end
  
  resources :items do
    collection do
      get 'search'
    end
  end
  
  resources :users
  resources :realms,        :only => [:index]
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :bounds,        :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/admin',   :to => 'pages#admin'
  
  root :to => "pages#home"

  get "pages/contact"
  get "pages/search"

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :realm
  
  has_many :relationships,  :dependent => :destroy
  has_many :owners,         :through => :relationships, :source => :user
  
  validates :name,    :presence => true
  validates :realm_id,  :presence => true
  validates_uniqueness_of :name, :scope => :realm_id
  
  attr_accessor :inventory, :lastModified
  
  def update_from_battlenet?
    battlenet = Character.get_from_battlenet(self.realm.region, self.realm.slug, self.name)    
    unless battlenet.nil?
      return self.update_attributes(battlenet) ? true : false
    end
    return false
  end
  
  def self.find_by_realm(region, realm, name)
    if realm = Realm.find_by_region_and_name(region, realm)
      if character = realm.characters.find_by_name(name.capitalize)
        return character
      end
    end
  end
  
  def self.find_by_realm_id(realm_id, name)
    character = Realm.find_by_id(realm_id).characters.find_by_name(name.capitalize)
  end
  
  def self.get_from_battlenet(region, realm_slug, name)
    bn = Battlenet::get_character(region, realm_slug, name, 'items')
    if bn[:status].nil?
      bn.delete(:realm)
      bn.delete(:status)
      bn[:items] = bn[:items].to_s unless bn[:items].nil?
      return bn
    end
    
    return nil
  end
  
  def self.find_or_create(region, realm, name)
    
    unless @character = Character.find_by_realm(region, realm, name)
      bn = Character.get_from_battlenet(region, realm, name)
      realm = Realm.find_by_region_and_name(region, realm)
      @character = realm.characters.create(bn) if realm
    end
    
    (@character.nil? || @character.id.nil?) ? nil : @character
  end
  
  def create_inventory
    
    self.items = eval(self.items ||= "{}")
    @inventory = []
    self.items.each do |k,v|
      if v.is_a?(Hash)
        if i = Item.find_or_create(v[:id])
          i.tooltipParams = v[:tooltipParams]
          @inventory << i
        end
      end
    end
  end
  
  #Gotta update the time manually since it's comes on Java and not Unix format
  def lastModified=(time)
    @lastModified = Time.at(time/1000)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :admin_user, :only => [:destroy]
  def show
    if @character = Character.find_by_id(params[:id])
      @title = "#{@character.realm.name} | #{@character.name}"
      @character.create_inventory
      @relationship = current_user.claimed?(@character) if current_user
    else
      render 'search'
    end
  end
  
  def index
    @title = "Characters"
    @characters = Character.order("id DESC").limit(10)
  end
  
  def update
    @character = Character.find(params[:id])
    
    if @character.update_from_battlenet?
      flash[:success] = "We have updated #{@character.name} from Battle.net!"
      redirect_to @character
    else
      name = @character.name
      @character.delete
      flash.now[:error] = "We could not find #{name} at Battle.net!"
      render 'search'
    end    
  end
  
  def search
    @title = "Search"
    
    params[:name].gsub!(/ /,'')
    realm = Realm.find_by_id(params[:realm][:id])
    
    @character = Character.find_or_create('us', realm.name, params[:name])
    if @character.nil?
      flash[:error] = "We were unable to find #{realm.name}/#{params[:name]} in Battle.net"
      redirect_to characters_path
    else
      redirect_to @character
    end
  end
  
  def destroy
    char = Character.find(params[:id])
    char.destroy
    flash[:success] = "Character #{char.name}/#{char.realm.name} destroyed."   
    redirect_to admin_path
  end
end

app/helpers/characters_helper.rb
module CharactersHelper

  
  
  def compare_by_level(iLevel,cLevel)
    if iLevel < cLevel
      return 'below'
    else iLevel > cLevel
      return 'above'
    end
  end  
end

app/views/characters/_bind.html.erb
<%= form_for @relationship.bounds.build(:item_id => item.id), 
    # :remote => true 
	do |f| %> 
    <div><%= f.hidden_field :item_id %><%= f.hidden_field :persona_id %><%= f.hidden_field :persona %></div>
    <div class="actions"><%= f.submit "Bind" %></div>
<% end %>

app/views/characters/_binding_form.html.erb
<% if signed_in? %>
  <div id="binding_form">
    <% if @relationship.bound?(item) %>
      <%= render 'unbind', :item => item %>
    <% else %>
      <%= render 'bind', :item => item %>
    <% end %>
  </div>
<% end %>

app/views/characters/_character.html.erb
<div class = "round character-compact">
	<div class="left">
		<%= character_image character.thumbnail, :size => "40x40" %>
	</div>
	<div class="info-compact"> 
		<strong><%= link_to character.name, character %> - <%= character.level %></strong><br />
		<strong>Achievement Points:</strong> <%=character.achievementPoints%>
	</div>
</div>

app/views/characters/_search_form.html.erb
<%= form_tag search_characters_path, :method => 'get' do %>
  <div class="field">
    <%= label_tag :region %><br />
    <%= select_tag(:region, options_for_select(Battlenet::get_regions, Battlenet::get_regions.map {|v| [v, v]})) %>

  </div>
  <div class="field">
    <%= label_tag :realm %><br />
    <%= collection_select(:realm, :id, Realm.all, :id, :name)%>
  </div>
  <div class="field">
    <%= label_tag :name %><br />
    <%= text_field_tag :name, params[:name] %>
  </div>  
  <%= submit_tag "Search", :name => nil %>
<% end %> 

app/views/characters/_unbind.html.erb
<%= form_for @relationship.bounds.find_by_item_id(item), 
    :html => {:method => :delete},
    # :remote => true 
	do |f| %>
	<div><%= f.hidden_field :persona_id %><%= f.hidden_field :persona %></div>
    <div class="actions"><%= f.submit "Unbind" %></div>
<% end %>

app/views/characters/index.html.erb
<h1>Characters</h1>
<hr />
<h2>Search for your character</h2>
<%= render 'search_form'%>
<hr />
<h2>Latest Additions</h2>
<%= render @characters %>

app/views/characters/search.html.erb
<%= render 'search_form' %>

app/views/characters/show.html.erb
<div class="span-12">
  <div class="top left">
    <%= character_image @character.thumbnail %>
  </div>
  <div class="prepend-3">
    <h1><%= @character.name %></h1>
    <h2><%= "#{@character.level}  #{Battlenet::races[@character.race][:name]} #{Battlenet::klass[@character.klass][:name]}" %><br />
        <%= "#{@character.realm.region.upcase} / #{@character.realm.name}" %></h2>
  </div>
</div>

<div class="span-12 last">
  <div class ="right">
    <%= button_to "Update", character_path(@character), :method => :put %>
    <%= render 'users/claim_form' %>
  </div>
  
  <strong>Last Modified:</strong> <%= @character.lastModified %><br />             
  <strong>Realm:</strong> <%= @character.realm.name %><br />             
  <strong>Level:</strong> <%= @character.level %><br />            
  <strong>Item Level:</strong> <%= @character.items[:averageItemLevel] %><br />
  <strong>Item Level Equipped:</strong> <%= @character.items[:averageItemLevelEquipped] %>
</div>

<hr />

<div class="outfit">
  <table>
    <tr>
      <th>Slot</th>
      <th>Item</th>
      <th>Gems</th>
      <th>Enchanted?</th>
      <th>Reforged?</th>
      <th>Level</th>
    <tr>
  <% @character.inventory.each do |v| %>
    <tr>
      <td><strong><%= Battlenet::Item::InventoryType[v[:inventoryType]] %></strong></td>
      <td class="<%= Battlenet::quality[v[:quality]] %>"><%= link_to v[:name], item_path(v[:id]), :rel => "item=#{v[:id]}" %></td>
      <td><%= link_to '#', item_path(v.tooltipParams[:gem0]), :rel =>  "item=#{v.tooltipParams[:gem0]}" if  v.tooltipParams[:gem0] %>
          <%= link_to '#', item_path(v.tooltipParams[:gem1]), :rel =>  "item=#{v.tooltipParams[:gem0]}" if  v.tooltipParams[:gem1] %>
          <%= link_to '#', item_path(v.tooltipParams[:gem2]), :rel =>  "item=#{v.tooltipParams[:gem0]}" if  v.tooltipParams[:gem2] %></td>
      <td><%= "Yes" if v.tooltipParams[:enchant] %></td>
      <td><%= "Yes" if v.tooltipParams[:reforge] %></td>
      <td><%= v[:itemLevel] %></td>
    </tr>
  <% end %>
  </table>
</div>

<% if @relationship %>

<hr />

  <div class="span-12 colborder">
    <h2>Account Items</h2>

    <% current_user.unique_items(@relationship).each do |item| %>
	  <div class="item_small round <%= compare_by_level item.itemLevel, @character.items[:averageItemLevel] %>">	
		<div class="top right">
		  <%= render 'binding_form', :item => item %>
		</div>
		<div class="left">
		  <%= icon_image item.icon, :size => "40x40" %>
		</div>
		<div class="info-compact <%= Battlenet::quality[item.quality] %> item"> 
		  <strong><%= link_to_item item %></strong>
		</div>
	  </div>
    <% end %>	
  </div>

  <div class="span-12 last">
    <h2>Character Items</h2>
	
    <% @relationship.items.each do |item| %>
	  <div class="item_small round <%= compare_by_level item.itemLevel, @character.items[:averageItemLevel] %>">	
		<div class="top right">
		  <%= render 'binding_form', :item => item %>
		</div>
		<div class="left">
		  <%= icon_image item.icon, :size => "40x40" %>
		</div>
		<div class="info-compact <%= Battlenet::quality[item.quality] %> item"> 
		  <strong><%= link_to_item item %></strong>
		</div>
	  </div>
    <% end %>	
    
  </div>
<% end %>  