config/routes.rb
WowWishlist::Application.routes.draw do

  resources :characters do
    collection do
      get 'search'
    end
  end
  
  resources :items do
    collection do
      get 'search'
    end
  end
  
  resources :users
  resources :realms,        :only => [:index]
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :bounds,        :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/admin',   :to => 'pages#admin'
  
  root :to => "pages#home"

  get "pages/contact"
  get "pages/search"

end

app/models/item.rb
class Item < ActiveRecord::Base
  
  validates :id,    :presence => true
  validates :name,  :presence => true
  validates :icon,  :presence => true
  
  has_many :bounds,     :dependent => :destroy
  
  attr_accessor :tooltipParams
  
  def self.find_or_create(item_id) 
    
    unless item = Item.find_by_id(item_id)
      if item  = Item.new(get_from_battlenet(item_id)) 
        item.id = item_id
        item.save
      end
    end
    
    item.valid? ? item : nil
  end
  
  def self.get_from_battlenet(item_id)
    bn = Battlenet::get_item(item_id)
    
    if bn[:status].nil?
      bn[:bonusStats] = bn[:bonusStats].to_s unless bn[:bonusStats].nil?
      bn[:itemSpells] = bn[:itemSpells].to_s unless bn[:itemSpells].nil?
      bn[:itemSource] = bn[:itemSource].to_s unless bn[:itemSource].nil?
      bn[:weaponInfo] = bn[:weaponInfo].to_s unless bn[:weaponInfo].nil?
      bn[:socketInfo] = bn[:socketInfo].to_s unless bn[:socketInfo].nil?
      return bn
    end
    return nil
  end
  
  def prepare!
    self.bonusStats = eval(self.bonusStats) if self.bonusStats
    self.itemSpells = eval(self.itemSpells) if self.itemSpells
    self.itemSource = eval(self.itemSource) if self.itemSource
    self.weaponInfo = eval(self.weaponInfo) if self.weaponInfo
    self.socketInfo = eval(self.socketInfo) if self.socketInfo
    return self
  end
end  

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :user_admin, :only => [:destroy, :update]
  
  def show
    @item = Item.find_or_create(params[:id]).prepare!
    @title = "Item | #{@item.name}"
  end
  
  def index
    @title = "Items"
    category = params[:c] || 'id'
    direction = params[:d] || 'DESC'
    quantity = params[:q] || 20
    @items = Item.order("#{category} #{ direction }").paginate(:page => params[:page], :per_page => quantity)
  end
  
  def search
    if @item = Item.find(:first, :conditions => ["name LIKE ?", params[:id]])
      redirect_to @item
    elsif @item = Item.find_or_create(params[:id].to_i)
      redirect_to @item
    else
      flash[:error] = "We were unable to find [#{params[:id]}] in our database or Battle.net."
      flash[:notice] = "If you entered a name, please try the item id instead!"
      redirect_to items_path
    end
  end
  
  def destroy
    item = Item.find(params[:id])
    item.destroy
    flash[:success] = "Item [#{item.id}] #{item.name} destroyed."
    redirect_to admin_path
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<div class = "round item-compact item_small">
  <% unless local_assigns[:persona].nil? %>	
	<div class="top right">
		<%= render 'shared/binding_form', :persona => persona,  :item => item %>
	</div>
  <% end %>
	<div class="left">
		<%= icon_image item.icon, :size => "40x40" %>
	</div>
  <% if local_assigns[:persona] && persona.is_a?(Relationship) 
	   persona.character.create_inventory.each 
	
	 end
	%>
	<div class="info-compact <%= Battlenet::quality[item.quality] %> item"> 
		<strong><%= link_to_item item %></strong><br />
	</div>
</div>

app/views/items/_search.html.erb
<h2>Search for Items</h2>
<%= form_tag search_items_path, :method => 'get' do %>
  <div class="field">
    <%= text_field_tag :id, params[:name] %> 
	<%= submit_tag "Search" %>
  </div>  
<% end %>

app/views/items/_stats.erb
<div>
  <%= Battlenet::Item::Bind[item.itemBind] %> <br />
  <%= Battlenet::Item::InventoryType[item.inventoryType] %>
</div>

<% if item.itemClass == 2 %>
  <div>
    <%= "#{item.weaponInfo[:damage][0][:minDamage]} - #{item.weaponInfo[:damage][0][:maxDamage]} Damage" %> <br />
    <%= "Speed #{item.weaponInfo[:weaponSpeed]}" %> <br />
    <%= "(#{item.weaponInfo[:dps].round(1)} damage per second)" %>
  </div>
<% end %>

<div class="simpleStats">
  <% item.bonusStats.each do |stat| %>
    <% if [1,2,3,4,5,6,7].include?(stat[:stat]) %>
      <%= "#{Battlenet::Item::Stat_print[stat[:stat]] % stat[:amount]}" %><br />
    <% end%>
  <% end %>
</div>

<div>
  <%= "Durability #{item.maxDurability}/#{item.maxDurability}" unless item.maxDurability <= 0 %><br />
  <%= "Item Level #{item.itemLevel}" unless item.itemLevel.nil? %><br />  
  <%= item.description unless item.description.nil? %>
</div>

<div class="simpleStats Uncommon">
  <% item.bonusStats.each do |stat| %>
    <% unless [1,2,3,4,5,6,7].include?(stat[:stat]) %>
      <%= "#{Battlenet::Item::Stat_print[stat[:stat]] % stat[:amount]}" %><br />
    <% end%>
  <% end %>
</div>

app/views/items/index.html.erb
<h1>Items</h1>
<%= render 'search' %>
<hr />
<h2>Latest Additions</h2>

<%= will_paginate %>

<hr class="space" />
<table class="outfit">
  <tr>
    <th><%= sort_link 'Slot', :inventoryType %></th>
    <th><%= sort_link 'Item', :name %></th>
	<th><%= sort_link 'Class', :itemClass %></th>
	<th><%= sort_link 'Subclass', :itemSubClass %></th>
    <th><%= sort_link 'Level', :itemLevel %></th>
  <tr>
<% @items.each do |v| %>
  <tr>
    <td><strong><%= Battlenet::Item::InventoryType[v[:inventoryType]] %></strong></td>
    <td class="<%= Battlenet::quality[v[:quality]] %>"><%= link_to v[:name], item_path(v[:id]), :rel => "item=#{v[:id]}" %></td>
	<td><%= Battlenet::Item::Class[v[:itemClass]] %></td>
	<td><%= Battlenet::Item::Subclass[v[:itemClass]][v[:itemSubClass]].first %></td>
    <td><%= v[:itemLevel] %></td>
  </tr>
<% end %>
</table>

<%= will_paginate %>

app/views/items/show.html.erb
<div class="left">
  <%= icon_image @item.icon %>
  <hr />
  <%= render 'shared/binding_form', :persona => current_user, :item => @item if signed_in? %>
</div>
<div class="span-10 tooltip_border">
  <h2 class="<%= Battlenet::quality[@item.quality] %>"><%= @item.name %></h2>
  <div>
    <%= render 'stats', :item => @item %>

  </div>
</div>