config/routes.rb
WowWishlist::Application.routes.draw do

  resources :characters do
    collection do
      get 'search'
    end
  end
  
  resources :items do
    collection do
      get 'search'
    end
  end
  
  resources :users
  resources :realms,        :only => [:index]
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :bounds,        :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/admin',   :to => 'pages#admin'
  
  root :to => "pages#home"

  get "pages/contact"
  get "pages/search"

end

app/views/layouts/_footer.html.erb
<footer>
  <hr />
  <h2 class="alt">
    An on-going project by <%= link_to 'Juan Delgado', 'http://www.darksoda.com' %>, 
    located @ <%= link_to 'github', 'https://github.com/roloenusa/wow-wishlist' %>.
  </h2>
  <%= debug (params) if Rails.env.development? %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1><em class="alt">The</em> Woshlist<em class="alt">!</em></h1>
  <h2 class="alt">Don't lose your items again...</h2>
  <hr />
  <nav class="round">
	<ul>
	  <li><%= link_to 'Characters', characters_path %></li>
	  <li><%= link_to 'Items', items_path %></li>
    <% if signed_in? %>
	  <% if current_user.admin? %>
	    <li><a href="<%= admin_path %>">Admin</a></li>
      <% end %>
      <li><%= link_to current_user.name, current_user %> | </li>  
      <li><a href="<%= signout_path %>">Sign Out</a></li>
    <% else %>
      <li><a href="<%= signin_path %>">Sign In</a></li>
    <% end %>
    </ul>
  </nav>
  <hr />
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>a
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<!-- Import fancy-type plugin for the sample page. --> 
<%= stylesheet_link_tag 'blueprint/plugins/fancy-type/screen.css', :media => "screen, projection" %> 

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="utf-8"?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" > 
  <head> 
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
     
    <!-- Wowhead tooltips -->
    <%= javascript_include_tag "http://static.wowhead.com/widgets/power.js" %>
  </head>
  <body>
  
    <div class="container">
      <%= render 'layouts/header' %>
      
      <section class="round">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key} span-24") %>
        <% end%>
        <%= yield %>
      </section>
      
      <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>